House keeping

diff --git a/scripts/i3resize b/scripts/i3resize
--- a/scripts/i3resize
+++ b/scripts/i3resize
@@ -1,1 +1,27 @@
-/home/beron/Code/.dotfiles/i3cmds/i3resize
+#!/bin/sh
+# This script was made by `goferito` on Github.
+# Some cleanup by Luke.
+
+[ -z "$1" ] && echo "No direction provided" && exit 1
+[ -z "$2" ] && distance="$2 px or $2 ppt" || distance="5 px or 5 ppt"
+
+moveChoice() {
+  i3-msg resize "$1" "$2" "$distance" | grep '"success":true' || \
+    i3-msg resize "$3" "$4" "$distance"
+}
+
+case $1 in
+	up)
+		moveChoice grow up shrink down
+		;;
+	down)
+		moveChoice shrink up grow down
+		;;
+	left)
+		moveChoice shrink right grow left
+		;;
+	right)
+		moveChoice grow right shrink left
+		;;
+esac
+
